package dev.digitaldragon.jobs;

import lombok.Getter;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.function.Consumer;

/**
 * Run a system command (start a process) and handle the logs generated by it. Logs
 * are logged to the provided consumer.
 */
public class RunCommand {
    private final String[] args;
    private final Consumer<String> logger;
    private final File directory;
    @Getter
    private Process process;

    public RunCommand(String[] args, File directory, Consumer<String> logger) {
        this.args = args;
        this.directory = directory;
        this.logger = logger;
    }

    /**
     * Executes a command and returns the associated process.
     *
     * @return the Process object that was created by executing the command, or null if an IOException occurs
     */
    public Process run() {
        try {

            ProcessBuilder processBuilder = getExecutingProcess(args, directory);
            logger.accept("----- Bot: command: " + Arrays.toString(args) + " -----");
            processBuilder.redirectErrorStream(true);
            handleLogs(processBuilder);
            return process;
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Handles the logs generated by a process.
     *
     * @param processBuilder  the processbuilder to execute
     * @throws IOException if an I/O error occurs
     */
    public void handleLogs(ProcessBuilder processBuilder) throws IOException {
        process = processBuilder.start();
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8));
        StringBuilder logBuilder = new StringBuilder();
        int c;
        while ((c = reader.read()) != -1) {
            char character = (char) c;

            // Handle both '\n' and '\r' as newline characters
            if (character == '\n' || character == '\r') {
                String logLine = logBuilder.toString(); // Get the completed line
                logger.accept(logLine);
                logBuilder = new StringBuilder(); // Reset the StringBuilder for the next line

            } else {
                logBuilder.append(character); // Add the character to the current line
            }
        }

        // After the loop, check if there's an incomplete line to add
        if (!logBuilder.isEmpty()) {
            String logLine = logBuilder.toString();
            logger.accept(logLine);
        }
    }

    public int waitFor() {
        try {
            int exitCode = process.waitFor();
            logger.accept("----- Bot: Exit code: " + exitCode + " -----");
            return exitCode;
        } catch (InterruptedException e) {
            LoggerFactory.getLogger(RunCommand.class).error("Error waiting for process", e);
            logger.accept("----- Bot: Error waiting for process -----");
        }
        logger.accept("----- Bot: Something went wrong... -----");
        logger.accept("This error likely originates from somewhere within wikibot. Please report this!");

        return 999;
    }

    /**
     * Creates a process to execute a command.
     * @param args The args to be passed to the process, including the command name/process name
     * @param dumpsDir The directory where the process will be executed
     * @return the executing process
     * @throws IOException if an I/O error occurs
     */
    public static ProcessBuilder getExecutingProcess(String[] args, File dumpsDir) throws IOException {
        ProcessBuilder processBuilder = new ProcessBuilder(args);
        processBuilder.directory(dumpsDir);
        processBuilder.redirectErrorStream(true);
        return processBuilder;
    }
}
