package dev.digitaldragon.jobs;

import lombok.Getter;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

public class RunCommand {
    private final String command;
    private final StringLogHandler handler;
    private final File directory;
    @Getter
    private Process process;

    public RunCommand(String command, File directory, StringLogHandler handler) {
        this.command = command;
        this.directory = directory;
        this.handler = handler;
    }

    public Process run() {
        try {
            handler.onMessage("----- Bot: command: " + command + " -----");

            ProcessBuilder processBuilder = getExecutingProcess(command, directory);
            processBuilder.redirectErrorStream(true);
            handleLogs(processBuilder);
            return process;
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Handles the logs generated by a process.
     *
     * @param processBuilder  the processbuilder to execute
     * @throws IOException if an I/O error occurs
     */
    public void handleLogs(ProcessBuilder processBuilder) throws IOException {
        process = processBuilder.start();
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8));
        StringBuilder logBuilder = new StringBuilder();
        int c;
        while ((c = reader.read()) != -1) {
            char character = (char) c;

            // Handle both '\n' and '\r' as newline characters
            if (character == '\n' || character == '\r') {
                String logLine = logBuilder.toString(); // Get the completed line
                handler.onMessage(logLine);
                logBuilder = new StringBuilder(); // Reset the StringBuilder for the next line

            } else {
                logBuilder.append(character); // Add the character to the current line
            }
        }

        // After the loop, check if there's an incomplete line to add
        if (!logBuilder.isEmpty()) {
            String logLine = logBuilder.toString();
            handler.onMessage(logLine);
        }
    }

    /**
     * Creates a process to execute a command in Powershell or Bash based on operating system.
     *
     * @param command  the command to be executed
     * @param dumpsDir the directory where the process will be executed
     * @return the executing process
     * @throws IOException if an I/O error occurs
     * @throws UnsupportedOperationException if the operating system is not supported
     */
    @NotNull
    public static ProcessBuilder getExecutingProcess(String command, File dumpsDir) throws IOException {
        ProcessBuilder processBuilder;
        String os = System.getProperty("os.name").toLowerCase();

        if (os.contains("win")) { // For Windows
            processBuilder = new ProcessBuilder("powershell.exe", "/c", command);
        } else if (os.contains("nix") || os.contains("nux") || os.contains("mac")) { //For Unix-based
            processBuilder = new ProcessBuilder("/bin/bash", "-c", command);
        } else {
            throw new UnsupportedOperationException("Unsupported operating system: " + os);
        }
        processBuilder.directory(dumpsDir);
        processBuilder.redirectErrorStream(true);

        return processBuilder;
    }
}
